image: Ubuntu2004

install:
- sh: sudo chmod 777 gradlew

build_script:
- sh: ./gradlew assemble --info --stacktrace --console=plain --max-workers=1 --no-daemon --build-cache -Dkotlin.colors.enabled=false
