image: Ubuntu2004

cache:
- /home/appveyor/.gradle/caches
- /root/.gradle/caches
- /root/.konan/cache

install:

#openal
- sh: sudo apt-get -y install libopenal-dev
#python
- sh: sudo apt-get -y install libpython3.9 --fix-missing
- sh: sudo apt-get -y install python3.9-full
- sh: sudo apt-get -y install python3.9-dev
#pip
- sh: sudo wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
- sh: sudo python3 get-pip.py
- sh: sudo python3 -m pip install --upgrade pip
- sh: sudo python3 -m pip install --upgrade setuptools 
- sh: sudo python3 -m pip install --upgrade wheel
#build tools
- sh: sudo python3 -m pip install meson
- sh: sudo python3 -m pip install ninja
- sh: sudo python3 -m pip install cmake
- sh: sudo mkdir -p build/gtk4
- sh: sudo mkdir -p build/glib2
- sh: sudo mkdir -p build/pango
- sh: sudo mkdir -p build/vulkan
#midi
- sh: sudo apt-get -y install libjack-dev
- sh: sudo apt-get -y install alsa-base alsa-source alsa-tools 
- sh: sudo apt-get -y install alsa-utils libalsaplayer-dev
- sh: sudo mkdir -p build/rtmidi
- sh: sudo git clone https://github.com/thestk/rtmidi.git build/rtmidi
- sh: sudo git --work-tree=build/rtmidi --git-dir=build/rtmidi/.git checkout tags/4.0.0 -b 4.0.0
- sh: sudo mkdir -p build/rtmidi/_build
- sh: sudo cmake build/rtmidi -B build/rtmidi/_build -DCMAKE_INSTALL_PREFIX=/usr
- sh: sudo cmake --build build/rtmidi/_build --target install


build_script:
- sh: echo hello worl
