image: Ubuntu2004

cache:
- /home/appveyor/.gradle/caches
- /root/.gradle/caches
- /root/.konan/cache

install:
- sh: sudo apt-get -y install mathgl
- sh: sudo ls /usr/include/mgl2

build_script:
- sh: echo hello
