image: Ubuntu2004

cache:
- /home/appveyor/.gradle/caches
- /root/.gradle/caches
- /root/.konan/cache

install:
- sh: sudo chmod 777 gradlew
- sh: sudo cp data_cf_bool.h /usr/include
- sh: sudo chmod -R 755 /usr/include/data_cf_bool.h
- sh: sudo apt-get -y install libncurses5
- sh: sudo apt-get update
- sh: sudo apt-get -y install libegl1-mesa libegl1-mesa-dev
- sh: sudo apt-get -y install libgles2-mesa-dev libglfw3-dev libglfw3
- sh: sudo apt-get -y install libglew-dev libglew2.1 freeglut3-dev
- sh: sudo mkdir build
- sh: sudo mkdir build/mathgl-2.4.4
- sh: sudo wget --no-check-certificate -c "https://nchc.dl.sourceforge.net/project/mathgl/mathgl/mathgl 2.4.4/mathgl-2.4.4.tar.gz" -O - | sudo tar -xz -C build
- sh: sudo mkdir build/mathgl-2.4.4/_build
- sh: sudo cmake build/mathgl-2.4.4 -B build/mathgl-2.4.4/_build -DCMAKE_INSTALL_PREFIX=/usr
- sh: sudo cmake --build build/mathgl-2.4.4/_build --target install
- sh: sudo ls /usr/include/mgl2

build_script:
- sh: sudo ./gradlew assemble --info --stacktrace --console=plain --max-workers=1 --no-daemon --build-cache -Dkotlin.colors.enabled=false -Dhttps.protocols=SSLv3,TLSv1,TLSv1.1,TLSv1.2
