image: Ubuntu2004

cache:
- /home/appveyor/.gradle/caches
- /root/.gradle/caches
- /root/.konan/cache

install:
- sh: sudo chmod 777 gradlew
- sh: sudo apt-get -y install libncurses5
- sh: sudo apt-get -y install mathgl
- sh: sudo ls /usr/include/mgl2

build_script:
- sh: sudo ./gradlew assemble --info --stacktrace --console=plain --max-workers=1 --no-daemon --build-cache -Dkotlin.colors.enabled=false -Dhttps.protocols=SSLv3,TLSv1,TLSv1.1,TLSv1.2
