image: Ubuntu2004
cache:
- /home/appveyor/.gradle/caches

install:
- sh: sudo chmod 777 gradlew
- sh: echo "$USER"
- sh: sudo mkdir -p /home/appveyor/.konan
- sh: sudo chmod -R 755 /home/appveyor/.konan
- sh: sudo chown appveyor:appveyor /home/appveyor/.konan
- sh: sudo apt-get -y remove --auto-remove --allow-downgrades --force-yes -allow-remove-essential --allow-change-held-packages  openjdk*
- sh: sudo apt-get -y purge --auto-remove --allow-downgrades --force-yes -allow-remove-essential --allow-change-held-packages  openjdk*
- sh: sudo apt-get -y install --allow-downgrades --force-yes -allow-remove-essential --allow-change-held-packages openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
- sh: sudo wget --no-check-certificate -c https://download.jetbrains.com/kotlin/native/builds/releases/1.5.20/linux/kotlin-native-prebuilt-linux-1.5.20.tar.gz -O - | tar -xz -C /home/appveyor/.konan/

build_script:
- sh: ./gradlew assemble --info --stacktrace --console=plain --max-workers=1 --no-daemon --build-cache -Dkotlin.colors.enabled=false -Dhttps.protocols=SSLv3,TLSv1,TLSv1.1,TLSv1.2
